### ISSUE TITLE
Fizz Buzz

### ISSUE THREAD

**Issue by DahliaSR** [CheckIO-to-German/Roadmap#1]
- [x] CheckIO-to-German/Fizz-Buzz#1
- [x] CheckIO-to-German/Fizz-Buzz#2
- [x] CheckIO-to-German/Fizz-Buzz#3
